# Generated by Django 5.2.1 on 2025-05-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
