# Generated by Django 5.2.1 on 2025-05-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
